baseURL = "https://wiki.phala.network"
languageCode = "en-us"
title = "Phala Network Wiki"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "phala"